
static int nstest(void);
static int	nsinit(int argc, char **argv);
static void nsusage(void);
static void nsloop(void);
static ELVBOOL nspoll(ELVBOOL reset);
static void nsterm(void);
static ELVBOOL nscreategw(char *name, char *attributes);
static void nsdestroygw(GUIWIN *gw, ELVBOOL force);
static ELVBOOL nsfocusgw(GUIWIN *gw);
static void nsretitle(GUIWIN *gw, char *name);
static void nsreset(void);
static void nsflush(void);
static void nsmoveto(GUIWIN *gw, int column, int row);
static void nsdraw(GUIWIN *gw, long fg, long bg, int bits, CHAR *text, int len);
static ELVBOOL nsshift(GUIWIN *gw, int qty, int rows);
static ELVBOOL nsscroll(GUIWIN *gw, int qty, ELVBOOL notlast);
static ELVBOOL nsclrtoeol(GUIWIN *gw);
static void nstextline(GUIWIN *gw, CHAR *text, int len);
static void nsbeep(GUIWIN *gw);
static ELVBOOL nsmsg(GUIWIN *gw, MSGIMP imp, CHAR *text, int len);
static void nsscrollbar(GUIWIN *gw, long top, long bottom, long nlines);
static ELVBOOL nsstatus(GUIWIN *gw, CHAR *cmd, long line, long column, _CHAR_ learn, char *mode);
static int nskeylabel(CHAR *given, int givenlen, CHAR **label, CHAR **raw);
static ELVBOOL nsclipopen(ELVBOOL forwrite);
static int nsclipwrite(CHAR *text, int len);
static int nsclipread(CHAR *text, int len);
static void nsclipclose(void);
static ELVBOOL nscolor(int fontcode, CHAR *colornam, ELVBOOL isfg, long *colorptr, unsigned char rgb[3]);
static void nsfreecolor(long color, ELVBOOL isfg);
static void nssetbg(GUIWIN *gw, long bg);
static ELVBOOL nsguicmd(GUIWIN *gw, char *extra);
static ELVBOOL nstabcmd(GUIWIN *gw, _CHAR_ key2, long count);
static void nssave(BUFFER buf, GUIWIN *gw);
static int nswildcard(char *names, char *buf, int bufsize, ELVBOOL single);
static ELVBOOL nsprgopen(char *command, ELVBOOL willwrite, ELVBOOL willread);
static int nsprgclose(void);
static RESULT nsstop(ELVBOOL alwaysfork);
